import numpy as np
import cv2
from skimage.morphology import skeletonize
from scipy.ndimage import distance_transform_edt
from skan import Skeleton, summarize


class VesselAnalyzer:
    def __init__(self, mask_pil):
        """
        Initializes with the PIL image mask generated by DeepSA[cite: 21, 25, 29].
        """
        # Convert PIL to binary numpy array (0 and 1)
        mask_np = np.array(mask_pil.convert('L'))
        self.binary_mask = (mask_np > 127).astype(np.uint8)
        self.skeleton = None
        self.distance_map = None

    def get_vessel_geometry(self):
        """
        Performs skeletonization and distance mapping to find vessel radii.
        """
        # 1. Skeletonization: Reduce vessels to 1-pixel centerlines
        self.skeleton = skeletonize(self.binary_mask)

        # 2. Distance Transform: Calculate radius at every point
        # distance_transform_edt gives the distance to the nearest background (0) pixel
        self.distance_map = distance_transform_edt(self.binary_mask)

        return self.skeleton, self.distance_map

    def calculate_stenosis(self, min_area=500):
        """
        Analyzes branches to find local minima in diameter[cite: 114, 115].
        """
        skel_obj = Skeleton(self.skeleton)
        summary = summarize(skel_obj)

        # We only analyze branches longer than a threshold to avoid noise
        branches = summary[summary['branch-distance'] > 20]

        blockages = []

        for index, row in branches.iterrows():
            # Get the path coordinates for this specific branch
            path_coords = skel_obj.path_coordinates(index).astype(int)

            # Extract radii along this branch from our distance map
            radii = self.distance_map[path_coords[:, 0], path_coords[:, 1]]
            diameters = radii * 2

            # Detect Local Minimum (D_min)
            d_min = np.min(diameters)
            min_idx = np.argmin(diameters)

            # Calculate Reference Diameter (D_ref)
            # We use the average of the 5 pixels at the start of the branch (proximal)
            d_ref = np.mean(diameters[:5])

            # Formula: (1 - D_min / D_ref) * 100
            if d_ref > 0:
                stenosis_percentage = (1 - (d_min / d_ref)) * 100

                # Flag if stenosis is clinically significant (>40%)
                if stenosis_percentage > 40:
                    blockages.append({
                        'coords': path_coords[min_idx],
                        'percentage': round(stenosis_percentage, 1),
                        'd_min': round(d_min, 2),
                        'd_ref': round(d_ref, 2)
                    })

        return blockages